# frozen_string_literal: true

module Dispersion
	module Tokens
		COMMENT = :COMMENT
		KEYWORD = :KEYWORD
		CONSTANT = :CONSTANT
		FUNCTION = :FUNCTION
		PUNCTUATION = :PUNCTUATION
		LOCAL_VARIABLE = :LOCAL_VARIABLE
		INSTANCE_VARIABLE = :INSTANCE_VARIABLE
		OPERATOR = :OPERATOR
		STRING = :STRING
		SYMBOL = :SYMBOL
		INTEGER = :INTEGER
		FLOAT = :FLOAT
	end
end
